CREATE TABLE IF NOT EXISTS user
(
    id        INT PRIMARY KEY AUTO_INCREMENT,
    token     VARCHAR(100) NOT NULL UNIQUE,
    uuid      VARCHAR(100) NOT NULL UNIQUE,
    timestamp TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);