name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: polling
        ports:
          - '3306:3306'
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=20

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest mysql-connector-python
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with ruff
      run: ruff check --output-format=github .
    - name: Debug MySQL Status
      run: docker ps -a
    - name: Run Tests
      env:
        DB_USER: root
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: 127.0.0.1
        DB_NAME: test
      run: pytest
    - name: Print Environment Variables
      run: env | grep DB_
      env:
        DB_USER: root
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: 127.0.0.1
        DB_NAME: test
